<a href="https://colab.research.google.com/github/VASAVI1231/pandas-filter-dataset-records/blob/main/pandas_filter_dataset_records.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Create dataset
data = {
    "Student": ["Ananya", "Rahul", "Sravani", "Kiran",
                "Priya", "Arjun", "Divya", "Manoj"],
    "Age": [20, 21, 19, 22, 20, 21, 19, 22],
    "Marks": [85, 72, 91, 64, 78, 55, 88, 70],
    "Attendance": [92, 81, 95, 74, 88, 69, 90, 79],
    "Department": ["AI", "CSE", "AI", "ECE",
                   "CSE", "ECE", "AI", "CSE"]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

# ---------------------------------
# Example 1: Marks greater than 80
# ---------------------------------

high_marks = df[df["Marks"] > 80]

print("Students with Marks greater than 80:")
display(high_marks)

# ---------------------------------
# Example 2: Attendance >= 90
# ---------------------------------

high_attendance = df[df["Attendance"] >= 90]

print("Students with Attendance >= 90:")
display(high_attendance)

# ---------------------------------
# Example 3: Multiple conditions
# Marks > 75 AND Attendance > 85
# ---------------------------------

good_performance = df[
    (df["Marks"] > 75) &
    (df["Attendance"] > 85)
]

print("Students with Marks > 75 AND Attendance > 85:")
display(good_performance)

# ---------------------------------
# Example 4: OR condition
# AI Department OR Marks > 85
# ---------------------------------

ai_or_high_marks = df[
    (df["Department"] == "AI") |
    (df["Marks"] > 85)
]

print("AI students OR students with Marks > 85:")
display(ai_or_high_marks)

# Number of records
print("Number of records in original dataset:", len(df))
print("Number of records after filtering:", len(good_performance))

Original Dataset:

   Student  Age  Marks  Attendance Department
0   Ananya   20     85          92         AI
1    Rahul   21     72          81        CSE
2  Sravani   19     91          95         AI
3    Kiran   22     64          74        ECE
4    Priya   20     78          88        CSE
5    Arjun   21     55          69        ECE
6    Divya   19     88          90         AI
7    Manoj   22     70          79        CSE

Students with Marks greater than 80:

   Student  Age  Marks  Attendance Department
0   Ananya   20     85          92         AI
2  Sravani   19     91          95         AI
6    Divya   19     88          90         AI

Students with Attendance >= 90:

   Student  Age  Marks  Attendance Department
0   Ananya   20     85          92         AI
2  Sravani   19     91          95         AI
6    Divya   19     88          90         AI

Students with Marks > 75 AND Attendance > 85:

   Student  Age  Marks  Attendance Department
0   Ananya   20     85          92         AI
2  Sravani   19     91          95         AI
4    Priya   20     78          88        CSE
6    Divya   19     88          90         AI

AI students OR students with Marks > 85:

   Student  Age  Marks  Attendance Department
0   Ananya   20     85          92         AI
2  Sravani   19     91          95         AI
6    Divya   19     88          90         AI

Number of records in original dataset: 8
Number of records after filtering: 4